receivers:
  otlp:
    protocols:
      grpc:
exporters:
  signalfx:
    realm: lab0
    access_token: ${SPLUNK_ACCESS_TOKEN}
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging]
    metrics:
      receivers: [otlp]
      exporters: [logging, signalfx]
